scripts: nvim: Small wrapper to handle directories better.

diff --git a/scripts/scripts/nvim b/scripts/scripts/nvim
--- a/scripts/scripts/nvim
+++ b/scripts/scripts/nvim
@@ -4,7 +4,18 @@ system_bin="/usr/bin/nvim"
 prelease_bin="${HOME}/.local/bin/nvim"
 
 if [ "${NVIM_VERSION:-"system"}" = "system" ]; then
-	"$system_bin" "$@"
+	bin="$system_bin"
 else
-	"$prelease_bin" "$@"
+	bin="$prelease_bin"
+fi
+
+if [ "$#" -eq 0 ]; then
+	"$bin"
+fi
+
+if [ "$#" -eq 1 ] && [ -d "$1" ]; then
+	cd "$1" || (echo "Can't cd to $1" && exit)
+	"$bin"
+	else
+	"$bin" "$@"
 fi
