Install only if building suceeded.

diff --git a/scripts/scripts/update_neovim b/scripts/scripts/update_neovim
--- a/scripts/scripts/update_neovim
+++ b/scripts/scripts/update_neovim
@@ -18,8 +18,14 @@ if [ "$1" != "--force" ] && [ "$(git pull)" = "Already up to date." ]; then
 	exit 0
 fi
 
-rm -rf /home/baleksa/.local/share/nvim/runtime && echo "Removed old VIMRUNTIME"
 make distclean && echo "Cleaned build dirs."
-make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local" && echo "Built nvim."
-
-make install && echo "Installed nvim."
+make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local"
+build_status=$?
+if [ "$build_status" = "0" ]; then
+	echo "Built nvim. Now installing."
+	rm -rf /home/baleksa/.local/share/nvim/runtime && echo "Removed old VIMRUNTIME"
+	make CMAKE_INSTALL_PREFIX="$HOME/.local" install && echo "Installed nvim."
+else
+	echo "Building nvim failed with exit code $build_status!"
+	exit $build_status
+fi
