Don't update unused tools.

diff --git a/scripts/scripts/update_mason_nvim b/scripts/scripts/update_mason_nvim
--- a/scripts/scripts/update_mason_nvim
+++ b/scripts/scripts/update_mason_nvim
@@ -9,16 +9,16 @@ update_mason_packages() {
 
 }
 
-update_solargraph_rails() {
-	solargraph_path="$mason_packages_path/solargraph"
-	cd "$solargraph_path" || {
-		echo "Failed to cd to $solargraph_path"
-		return 1
-	}
-
-	gem i --install-dir "$solargraph_path" \
-		solargraph-rails
-}
+# update_solargraph_rails() {
+# 	solargraph_path="$mason_packages_path/solargraph"
+# 	cd "$solargraph_path" || {
+# 		echo "Failed to cd to $solargraph_path"
+# 		return 1
+# 	}
+#
+# 	gem i --install-dir "$solargraph_path" \
+# 		solargraph-rails
+# }
 
 update_python_lsp_extensions() {
 	pylsp_path="$mason_packages_path/python-lsp-server"
@@ -68,11 +68,11 @@ if [ "$status" -ne 0 ]; then
 	exit "$status"
 fi
 
-update_solargraph_rails
-status="$?"
-if [ "$status" -ne 0 ]; then
-	echo "Adding solargraph-rails to solargraph failed with error $status"
-	exit "$status"
-fi
+# update_solargraph_rails
+# status="$?"
+# if [ "$status" -ne 0 ]; then
+# 	echo "Adding solargraph-rails to solargraph failed with error $status"
+# 	exit "$status"
+# fi
 
 exit 0
